### ISSUE TITLE
Question regarding the paper: "Mignis: A semantic based tool for firewall configuration"

### ISSUE THREAD

**Issue by abc127845** [secgroup/Mignis#3]
I just finished reading "Mignis: A semantic based tool for firewall configuration"
And I want know about "Mignis" technical proofs at reference 36 on this paper
![image](https://user-images.githubusercontent.com/23723642/55317049-57717800-54a2-11e9-8271-6a8bc4da0062.png)
![image](https://user-images.githubusercontent.com/23723642/55317121-77a13700-54a2-11e9-8ce5-27b2200413ae.png)

I couldn't find the relevant information on this paper[36] on the Internet.

Where can I find relevant information about it?

Thanks a lot!

**Comment by repnzscasb** [comment]
Hi, thanks for noticing that, you can find the extended version [here](https://www.math.tecnico.ulisboa.pt/~padao/projects/ComFormCrypt/report3/papers-submitted/SUB-Mignis.pdf). I'll update the readme as well.

**Comment by abc127845** [comment]
Thank you for your reply.

repnzscasb <notifications@github.com> 於 2019年4月1日 週一 下午6:25寫道：
